language: java
jdk:
  - openjdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
  - cd my-project
  - mvn dependency:tree

script:
  - mvn test -B