language: java
jdk:
  - openjdk8

services:
  - mysql
  -
before_install:
  - chmod +x ./mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:

script:
  - mvn test -B

after_script: